app/ext/result/models.py
from sqlalchemy import String, Column, Integer, DateTime, ForeignKey
from sqlalchemy.orm import relationship

from app.extensions import db
from app.models import ModelMixin
from app.ext.core.models import User

class Season(db.Model, ModelMixin):
    __tablename__ = "seasons"
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(255))
    date_start = db.Column(db.DateTime)
    tours = db.relationship("Tour", back_populates="season")


class Tour(db.Model, ModelMixin):
    __tablename__ = "tours"
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(255))
    season_id = db.Column(db.Integer, db.ForeignKey(Season.id))
    date_start = db.Column(db.DateTime)
    season = db.relationship("Season", back_populates="tours")
    matches = db.relationship("Match", back_populates="tour")


class Match(db.Model, ModelMixin):
    __tablename__ = "matches"
    id = db.Column(db.Integer, primary_key=True)
    # title = db.Column(db.String(255))
    tour_name = db.Column(db.String(10))
    tour_id = db.Column(db.Integer, db.ForeignKey(Tour.id))
    name1 = db.Column(db.String(25))
    name2 = db.Column(db.String(25))
    goal1 = db.Column(db.Integer)
    goal2 = db.Column(db.Integer)
    date_start = db.Column(db.DateTime)
    tour = db.relationship("Tour", back_populates="matches")
    predicts = db.relationship("Predict", back_populates="match")

    def __init__(self, data):
        self.id = data['id']
        self.tour_name = data['stageName']
        self.tour_id = data['stage']
        self.name1 = data['name1']
        self.name2 = data['name2']
        self.goal1 = data['goal1'] if data['goal1'] else "_"
        self.goal2 = data['goal2'] if data['goal2'] else "_"
        self.date = data['date']

    def __repr__(self):
        return f"Матч с id: {self.id}, {self.tour_name}: {self.name1} - {self.name2} {self.goal1}:{self.goal2} , {self.date}"

class Predict(db.Model, ModelMixin):
    __tablename__ = "predicts"
    id = db.Column(db.Integer, primary_key=True)
    match_id = db.Column(db.Integer, db.ForeignKey(Match.id))
    user_id = db.Column(db.Integer, db.ForeignKey(User.id))
    goal1 = db.Column(db.Integer)
    goal2 = db.Column(db.Integer)
    dt_predict = db.Column(db.DateTime)
    user = db.relationship("User", back_populates="predicts")
    match = db.relationship("Match", back_populates="predicts")

    def getResults():
        return results

app/ext/result/__init__.py
"""Расширение по результатам матчей."""

__version__ = "0.1.0"
__author__ = "Ademaro"

from .views import result

bps = [(result, "/results")]

app/ext/result/views/__init__.py
from flask import Blueprint, g, render_template

from app.utils import calc_points

result = Blueprint("result", __name__, template_folder="templates")


@result.get("")
def list():
    g.breadcrumbs = [{"title": "Результаты по турам"}]
    result_list = [1, 2, 3]
    return render_template("result/list.j2", tours=result_list)


@result.get("/<int:tour_id>")
def item(tour_id):
    g.breadcrumbs = [{"controller": ".list", "title": "Результаты по турам"}, {"title": f"Результаты {tour_id} тура"}]

    results = [{
        "title": "Спартак — Зенит",
        "result": "2:1",
        "predict": None,
    }, {
        "title": "Краснодар — ЦСКА",
        "result": "2:0",
        "predict": "2:1",
    }, {
        "title": "Ростов — Динамо",
        "result": "3:1",
        "predict": "3:1",
    }, {
        "title": "Крылья Советов — Урал",
        "result": "0:0",
        "predict": "1:1",
    }, {
        "title": "Рубин — Ахмат",
        "result": "2:0",
        "predict": "0:1",
    }, {
        "title": "Пари НН — Факел",
        "result": "2:0",
        "predict": "2:1",
    }, {
        "title": "Оренбург — Балтика",
        "result": "2:0",
        "predict": "0:1",
    }, {
        "title": "Сочи — Локомотив",
        "result": "2:0",
        "predict": "2:1",
    }]

    final_score = 0
    for match in results:
        match["score"] = calc_points(match["result"], match["predict"])
        final_score += match["score"]

    tour_results = {
        "title": f"Матчи {tour_id} тура (2024)",
        "final_score": final_score,
        "results": results
    }
    return render_template("result/item.j2", tour_id=tour_id, tour_results=tour_results)

app/templates/result/item.j2
{% extends "base.j2" %}

{% set title = "Тур" %}

{% block title %}
  <div class="col-lg-12 ml-auto">
    <h1 class="text-white">Результаты {{ tour_id }} тура</h1>
  </div>
{% endblock title %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <table class="table table-striped table-bordered table-dark table-hover">
          {# <caption>Результаты {{ tour_id }} тура</caption> #}
          <thead>
            <tr>
              <th scope="col">{{ tour_results.title }}</th>
              <th scope="col">Результаты матча</th>
              <th scope="col">Ваш прогноз</th>
              <th scope="col">Начислено очков</th>
            </tr>
          </thead>
          <tbody>
            {% for match in tour_results.results %}
              <tr>
                <th scope="row">{{ match.title }}</th>
                <td>{{ match.result }}</td>
                <td>{{ match.predict if match.predict else "_:_" }}</td>
                <td><span class="badge badge-info">{{ match.score }}</span></td>
              </tr>
            {% endfor %}
          </tbody>
          <tfoot>
            <tr class="bg-info">
              <th scope="col" colspan="3">Всего очков за тур</th>
              <th scope="col">{{ tour_results.final_score }}</th>
            </tr>
          </tfoot>
        </table>
      </div>
    </div>
  </div>
{% endblock content %}

app/templates/result/list.j2
{% extends "base.j2" %}

{% set title = "Результаты" %}
{% set page = "result.list" %}

{% block title %}
  <h1 class="text-white">Результаты по турам</h1>
{% endblock title %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <ul>
          {% for t_id in tours %}
            <li><a href="{{ url_for('result.item', tour_id=t_id) }}">Результаты {{ t_id }} тура</a></li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
{% endblock content %}