app/ext/suggestion/__init__.py
"""Расширение для предложений по улучшению сайта."""

__version__ = "0.1.0"
__author__ = "Ademaro"

from .views import suggestion

bps = [(suggestion, "/suggestions")]

app/ext/suggestion/views/__init__.py
from flask import Blueprint, g, render_template
from flask_security import current_user, login_required, roles_accepted

suggestion = Blueprint("suggestion", __name__, template_folder="templates")


@suggestion.get("")
def list():
    g.breadcrumbs = [{"title": "Предложения по улучшению сайта"}]
    suggestion_list = [1, 2, 3]
    # suggestion_links = [
    #     {"controller": "suggestions.list", "title": f"Предложение {suggestion_list[0]}"} for role in current_user.roles if role.name == "admin"
    # ]
    # if current_user.roles.name == "admin":
    return render_template("suggestion/list.j2", suggestions=suggestion_list)



@suggestion.get("/<int:suggestion_id>")
# @roles_accepted("admin")
def item(suggestion_id):
    return render_template("suggestion/item.j2", suggestion_id=suggestion_id)

app/templates/suggestion/item.j2
{% extends "base.j2" %}

{% set title = "Предложение по улучшению" %}

{% block title %}
  <h1 class="text-white">Предложение №{{ suggestion_id }}</h1>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta, molestias repudiandae pariatur.</p>
{% endblock title %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <p>В разработке...</p>
      </div>
    </div>
  </div>
{% endblock content %}

app/templates/suggestion/list.j2
{% extends "base.j2" %}

{% set title = "Предложения" %}
{% set page = "suggestion.list" %}

{% block title %}
  <h1 class="text-white">Список предложений по улучшению сайта</h1>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta, molestias repudiandae pariatur.</p>
{% endblock title %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <ul>
          {% for s_id in suggestions %}
            <li><a href="{{ url_for('suggestion.item', suggestion_id=s_id) }}">Предложение №{{ s_id }}</a></li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
{% endblock content %}