app/ext/prediction/__init__.py
"""Расширение по прогнозам на матч."""

__version__ = "0.1.0"
__author__ = "Ademaro"

from .views import prediction

bps = [(prediction, "/predictions")]

app/ext/prediction/views/__init__.py
from flask import Blueprint,g, render_template

prediction = Blueprint("prediction", __name__, template_folder="templates")


@prediction.get("")
def list():
    g.breadcrumbs = [{"title": "Прогнозы по турам"}]
    tours_list = [1, 2, 3]
    return render_template("prediction/list.j2", tours=tours_list)


@prediction.get("/<int:tour_id>")
def item(tour_id):
    g.breadcrumbs = [{"controller": ".list", "title": "Прогнозы по турам"}, {"title": f"Прогноз на {tour_id} тур"}]
    return render_template("prediction/item.j2", tour_id=tour_id)

app/templates/prediction/item.j2
{% extends "base.j2" %}

{% set title = "Тур" %}

{% block title %}
  <div class="col-lg-12 ml-auto">
    <h1 class="text-white">Прогноз на {{ tour_id }} тур</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta, molestias repudiandae pariatur.</p>
  </div>
{% endblock title %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <p>В разработке...</p>
      </div>
    </div>
  </div>
{% endblock content %}

app/templates/prediction/list.j2
{% extends "base.j2" %}

{% set title = "Прогнозы" %}
{% set page = "prediction.list" %}

{% block title %}
  <h1 class="text-white">Прогнозы по турам</h1>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta, molestias repudiandae pariatur.</p>
{% endblock title %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <ul>
          {% for t_id in tours %}
            <li><a href="{{ url_for('prediction.item', tour_id=t_id) }}">Тур {{ t_id }}</a></li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
{% endblock content %}