app/ext/core/views/user.py
from flask import Blueprint, current_app, flash, g, redirect, render_template, url_for
from flask_security import current_user, login_required

from app.ext.core.forms import EditProfileForm
from app.ext.core.models import User
from app.extensions import db

user = Blueprint("user", __name__, template_folder="templates")


@user.get("")
@login_required
def index():
    """Главная страница личного кабинета."""
    g.breadcrumbs = [{"title": "Личный кабинет"}]
    user_links = [
        {"controller": "user.edit", "title": "Изменить"},
        {"controller": "security.logout", "title": "Выйти"},
    ]
    user_links.extend(
        {"controller": "admin.index", "title": "Админка"} for role in current_user.roles if role.name == "admin"
    )
    return render_template("user/index.j2", user_links=user_links)


@user.route("/edit", methods=["GET", "POST"])
@login_required
def edit():
    """Редактирование данных пользователя."""
    g.breadcrumbs = [{"controller": ".index", "title": "Личный кабинет"}, {"title": "Изменить"}]
    current_user_db = User.query.get(current_user.id)
    edit_profile_form = EditProfileForm()
    if edit_profile_form.validate_on_submit():
        current_user_db.username = edit_profile_form.username.data
        current_user_db.firstname = edit_profile_form.firstname.data
        current_user_db.lastname = edit_profile_form.lastname.data
        current_user_db.us_phone_number = edit_profile_form.phone.data
        db.session.commit()
        flash("Сохранено", "success")
        return redirect(url_for("user.edit"))
    edit_profile_form.username.data = current_user_db.username
    edit_profile_form.firstname.data = current_user_db.firstname
    edit_profile_form.lastname.data = current_user_db.lastname
    edit_profile_form.phone.data = current_user_db.us_phone_number
    return render_template("user/edit_profile.j2", form=edit_profile_form)

app/templates/base.j2
{%- from "macros/menu.j2" import menu -%}
{%- from "macros/svg.j2" import icon -%}
<!DOCTYPE html>
<html lang="ru">
<head>
  <title>{{ title }}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">

  <link rel="stylesheet" href="{{ url_for('static', filename='fonts/icomoon/style.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='fonts/flaticon/font/flaticon.css') }}">

  {# <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}"> #}
  <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-datepicker.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/owl.carousel.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/owl.theme.default.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/jquery.fancybox.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/jquery-ui.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/aos.min.css') }}">

  <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.min.css') }}">
</head>
<body>
  <div class="site-wrap">
    <div class="site-mobile-menu site-navbar-target">
      <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close">
          <span class="icon-close2 js-menu-toggle"></span>
        </div>
      </div>
      <div class="site-mobile-menu-body"></div>
    </div>
    <header class="site-navbar py-4" role="banner">
      <div class="container">
        <div class="d-flex align-items-center">
          <div class="site-logo">
            <a href="{{ url_for('core.index') }}">
              <img src="{{ url_for('static', filename='images/logo.png') }}" alt="Logo">
            </a>
          </div>
          <div class="ml-auto">
            <nav class="site-navigation position-relative text-right" role="navigation">
              <ul class="site-menu main-menu js-clone-nav mr-auto d-none d-lg-block">
                {% if not current_user.is_authenticated %}
                  {{ menu(g.main_menu_not_auth, page) }}
                {% else %}
                  {{ menu(g.main_menu_auth, page) }}
                  {# <li class="li-lk">
                    <a class="nav-link" href="{{ url_for('user.index') }}"></a>
                  </li> #}
                {% endif %}
              </ul>
            </nav>
            <a href="#" class="d-inline-block d-lg-none site-menu-toggle js-menu-toggle text-black float-right text-white">
              <span class="icon-menu h3 text-white"></span>
            </a>
          </div>
        </div>

        {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
            {% for category, message in messages %}
              <div class="mt-3 alert alert-{{ category }} alert-dismissible fade show" role="alert">
                <strong>{{ message }}</strong>
                <button type="button" class="close" data-bs-dismiss="alert" aria-label="Закрыть"><span aria-hidden="true">&times;</span></button>
              </div>
            {% endfor %}
          {% endif %}
        {% endwith %}

        {% if g.breadcrumbs %}
          <nav class="mt-3" aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="{{ url_for('core.index') }}">Главная</a></li>
              {% for link in g.breadcrumbs %}
                {% if link.controller %}
                  <li class="breadcrumb-item"><a href="{{ url_for(link.controller) }}">{{ link.title }}</a></li>
                {% else %}
                  <li class="breadcrumb-item active" aria-current="page">{{ link.title }}</li>
                {% endif %}
              {% endfor %}
            </ol>
          </nav>
        {% endif %}
      </div>
      <div class="container">
        <div class="row align-items-center">
          <div class="col-lg-12 ml-auto">
            {% block title %}{% endblock title %}
          </div>
          <div class="col-lg-12 ml-auto">
            {% block content %}{% endblock content %}
          </div>
        </div>
      </div>
    </header>
    <div class="hero overlay" style="background-image: url({{ url_for('static', filename='images/bg_3.jpg') }});">

    </div>

    <div class="container">
      {% block subcontent %}{% endblock subcontent %}
    </div>

    <footer class="footer-section">
      <div class="container">
        <div class="row">
          <div class="col-lg-3">
            <div class="widget mb-3">
              <h3>News</h3>
              <ul class="list-unstyled links">
                <li><a href="#">All</a></li>
                <li><a href="#">Club News</a></li>
                <li><a href="#">Media Center</a></li>
                <li><a href="#">Video</a></li>
                <li><a href="#">RSS</a></li>
              </ul>
            </div>
          </div>
          <div class="col-lg-3">
            <div class="widget mb-3">
              <h3>Tickets</h3>
              <ul class="list-unstyled links">
                <li><a href="#">Online Ticket</a></li>
                <li><a href="#">Payment and Prices</a></li>
                <li><a href="#">Contact &amp; Booking</a></li>
                <li><a href="#">Tickets</a></li>
                <li><a href="#">Coupon</a></li>
              </ul>
            </div>
          </div>
          <div class="col-lg-3">
            <div class="widget mb-3">
              <h3>Matches</h3>
              <ul class="list-unstyled links">
                <li><a href="#">Standings</a></li>
                <li><a href="#">World Cup</a></li>
                <li><a href="#">La Lega</a></li>
                <li><a href="#">Hyper Cup</a></li>
                <li><a href="#">World League</a></li>
              </ul>
            </div>
          </div>

          <div class="col-lg-3">
            <div class="widget mb-3">
              <h3>Social</h3>
              <ul class="list-unstyled links">
                <li><a href="#">Twitter</a></li>
                <li><a href="#">Facebook</a></li>
                <li><a href="#">Instagram</a></li>
                <li><a href="#">Youtube</a></li>
              </ul>
            </div>
          </div>
        </div>

        <div class="row text-center">
          <div class="col-md-12">
            <div class=" pt-5">
              <p>
                Copyright &copy; 2024 All rights reserved | This site is made with <i class="icon-heart" aria-hidden="true"></i>
              </p>
            </div>
          </div>
        </div>
      </div>
    </footer>
  </div>
  <!-- .site-wrap -->
  <script src="{{ url_for('static', filename='js/jquery-3.3.1.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/jquery-migrate-3.0.1.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/jquery-ui.js') }}"></script>
  <script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/owl.carousel.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/jquery.stellar.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/jquery.countdown.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/bootstrap-datepicker.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/jquery.easing.1.3.js') }}"></script>
  <script src="{{ url_for('static', filename='js/aos.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/jquery.fancybox.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/jquery.sticky.js') }}"></script>
  <script src="{{ url_for('static', filename='js/jquery.mb.YTPlayer.min.js') }}"></script>

  <script src="{{ url_for('static', filename='js/script.js') }}"></script>
</body>
</html>